# ASP.NET Core
# Build and test ASP.NET Core projects targeting .NET Core.
# Add steps that run tests, create a NuGet package, deploy, and more:
# https://docs.microsoft.com/azure/devops/pipelines/languages/dotnet-core

trigger:
- master

pool:
  name: 'DEJAN-PC'
  #vmImage: 'windows-latest'

variables:
  buildConfiguration: 'Release'

steps:

- task: DotNetCoreCLI@2
  enabled: false
  displayName: "Build project"
  inputs:
    command: 'build'
    projects: '**/src/EntityFrameworkCore.SqlServer.Seeding/EntityFrameworkCore.SqlServer.Seeding.csproj'   

- task: DotNetCoreCLI@2
  displayName: "Pack NuGet package"
  inputs:
    command: 'pack'
    packagesToPack: '**/src/EntityFrameworkCore.SqlServer.Seeding/EntityFrameworkCore.SqlServer.Seeding.csproj'
    versioningScheme: 'off'

- task: DotNetCoreCLI@2
  enabled: true
  displayName: 'Push to Azure Artifact'
  inputs:
    command: 'push'
    packagesToPush: '$(Build.ArtifactStagingDirectory)/*.nupkg'
    nuGetFeedType: 'internal'
    publishVstsFeed: 'a75990cd-7350-4a40-8894-3fb9ec5869c1/b404b18e-3c67-48c1-90ee-bf3ada61ef30'
